use_frameworks!

platform :ios, '9.0'

target 'ModuleA_Example' do
  pod 'ModuleA', :path => '../'

  target 'ModuleA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
