use_frameworks!

platform :ios, '9.0'

target 'ModuleD_Example' do
  pod 'ModuleD', :path => '../'

  target 'ModuleD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
